name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Allow only one deployment at a time
concurrency:
  group: production-deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test || echo "No tests defined"

    - name: Build application
      run: npm run build || echo "No build script"

    - name: Deploy to server
      if: ${{ secrets.SERVER_HOST != '' }}
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /path/to/your/app
          git pull origin main
          npm install --production
          pm2 restart karaoke-app || pm2 start server.js --name karaoke-app

    - name: Skip deployment
      if: ${{ secrets.SERVER_HOST == '' }}
      run: echo "Server secrets not configured. Skipping deployment."